### ISSUE TITLE
migration to Django 1.7.x

### ISSUE THREAD

**Issue by mdiener21** [umap-project/django-leaflet-storage#103]
update to support Django 1.7.x I would like to get started on this if you have not already begun

**Comment by mdiener21** [comment]
django 1.7.x  getting the new migrations to work class Map calls Licence.get_default which cannot be serialized this method needs to move out of class License and into main, to be done soon.   As for the StreamingHttpResponse this is still outstanding with the Etag and Content-Length commented out.

**Comment by rtsisyk** [comment]
django 1.8 works well. I think this tickt can be closed.

**Comment by yohanboniface** [comment]
Good point!
