### ISSUE TITLE
Store datalayer in database

### ISSUE THREAD

**Issue by rtsisyk** [umap-project/django-leaflet-storage#104]
Hi Yohan!

What the point of storing datalayer in files?
I checked `git log` and found that versions before 0.5.0 stored markers and polylines directly in database. i think this approach was more flexible...

**Comment by almereyda** [comment]
I remember vaguely this was even considered a plus now, especially in direction of seperating the frontend from the API and the way it uses its storage backend(s).

Please also have a look at the pieces of said conversation at

* https://github.com/umap-project/umap/issues/80#issuecomment-127049552
* https://github.com/umap-project/umap/issues/80#issuecomment-127049553

**Comment by yohanboniface** [comment]
Yeah, as said by @almereyda this move has been made while trying to better seperate front and back ends.
The frontend now only deals with geojsons, and the backend is blind about the content of those geojson. Plus having those stored as files allow to use X-Accel-Redirects directive and make easier to provide a [basic versioning](https://github.com/umap-project/django-leaflet-storage/commit/d61ca9795b891dabac027da2fbdd3ba63f790d4f).
I know this also remove some ways of customizing how django-leaflet-storage works, but having no active community around this project, it move, little by little, to a pure backend for Leaflet.Storage and uMap, and it's not really a generic django app anymore.

Do you have specific use cases to put in the discussion?

**Comment by yohanboniface** [comment]
(Closing because, as for now, there is no action required here.)
