### ISSUE TITLE
Import geojson format

### ISSUE THREAD

**Issue by nordbit** [umap-project/django-leaflet-storage#105]
I have a problem with import data geojson from:
```
http://code.highcharts.com/mapdata/
```
I'am not geojson expert, is there a problem with format or leaflet-storage has no all feature to import that kind of data format?

**Comment by yohanboniface** [comment]
Possibly multipolygons or multipolylines. Try with the demo version, which is the future release: http://umap.fluv.io

**Comment by nordbit** [comment]
Norway map after import data in umap:
![umapnorway](https://cloud.githubusercontent.com/assets/1248229/10705268/093fc086-79dd-11e5-8993-ae1cc4ee6356.gif)

and same data in cartodb
![cartodbnorway](https://cloud.githubusercontent.com/assets/1248229/10705283/18afa752-79dd-11e5-8936-05fa64cabd3b.gif)

For you knowledge

**Comment by yohanboniface** [comment]
Sounds like projection issue.
I'll have a look.
Ref: https://github.com/umap-project/Leaflet.Storage/issues/104
