### ISSUE TITLE
Missing localisation files when install with pip

### ISSUE THREAD

**Issue by arbu** [umap-project/django-leaflet-storage#108]
I installed django-leaflet-storage via pip and the directory leaflet_storage/static/storage/src/locale/ only contains json files but not the according js files. Those should be generated (or prepackaged?) on installation in my opinion.

Also, when I tried to generate this files myself, I noticed that node.js is required for this, which i think is a bit too much as a build dependency. It would be nice to have simpler solution. Maybe loading the json file directly via AJAX would be an option?

**Comment by yohanboniface** [comment]
Sorry, missed the notification of this issue :(
You need to use `storagei18n` management command to generate locales files:

    python manage.py storagei18n
