### ISSUE TITLE
pip install downgrades Django

### ISSUE THREAD

**Issue by andybak** [umap-project/django-leaflet-storage#109]
$ pip install django-leaflet-storage
    Collecting Django==1.6.5 (from django-leaflet-storage)
      Using cached Django-1.6.5-py2.py3-none-any.whl
    Installing collected packages: Django
      Found existing installation: Django 1.9.2
        Uninstalling Django-1.9.2:

Even if your app is incompatible with newer Django versions - it should never do this. In fact - surely Django itself should not be in requirements.txt for an app that plugs into Django?

**Comment by andybak** [comment]
I also noticed psycopg2 is in the reqs: https://github.com/umap-project/django-leaflet-storage/blob/master/requirements.txt

**Comment by yohanboniface** [comment]
Watch out, by mistake you typed an exclamation mark at the end of the title of the issue ;)

**Comment by andybak** [comment]
Fixed  :)

**Comment by yohanboniface** [comment]
:)
So now you can just pip install again the Django version you want, and you're done :)

About the hard linking to specific Django version, humm, I'm balanced. If we have it open bar, we will end at some point with people installing an incompatible Django version. But its true that having this old version hard linked is not OK ;)

Maybe the best option is not to have Django in the requirements, but mentioning it in the install doc and letting users install what fit their needs?

About psycopg, yeah, let's remove it.

**Comment by andybak** [comment]
> Maybe the best option is not to have Django in the requirements, but mentioning it in the install doc and letting users install what fit their needs?

Yep - IMHO it should be a documentation thing, not an automated thing. Was rather confusing when ./manage.py migrate told me 'migrate' was an unknown command!

**Comment by andybak** [comment]
Looking at requirements.txt - if we remove Django and Psycopg that only leaves Pillow. And from a quick glance - I can't see any PIL imports in the code?
